# SPDX-License-Identifier: GPL-2.0


dtb-y += jlq_jr510.dtb

dtbo-y += jr510_evb01.dtbo \
	jr510_evb04.dtbo \
	jr510_evb05.dtbo \
	jr510_evb06.dtbo \
	jr510_c3mn.dtbo \
	jr510_evb05_power.dtbo \
	jr510_c3mnp0.dtbo \
	jr510_c3qp_india.dtbo \
	jr510_c3qp_international.dtbo \
	jr510_c3qp_redmi.dtbo \
	jr510_c3qr.dtbo \
	dsi_panel_boe_nt36525b.dtbo \
	dsi_panel_boe_nt36525b_lv.dtbo \
	dsi_panel_truly_ft8006saa.dtbo \
	dsi_panel_truly_ft8006saa_lv.dtbo \
	jr510_svc01.dtbo \
	jr510_svc02.dtbo \
	jr510_svc03.dtbo \
	jr510_svc04.dtbo

jr510_evb01.dtbo-base := jlq_jr510.dtb
jr510_evb04.dtbo-base := jlq_jr510.dtb
jr510_evb05.dtbo-base := jlq_jr510.dtb
jr510_evb06.dtbo-base := jlq_jr510.dtb
jr510_c3mn.dtbo-base := jlq_jr510.dtb
jr510_evb05_power.dtbo-base := jlq_jr510.dtb
jr510_c3mnp0.dtbo-base := jlq_jr510.dtb
jr510_c3qp_india.dtbo-base := jlq_jr510.dtb
jr510_c3qp_international.dtbo-base := jlq_jr510.dtb
jr510_c3qp_redmi.dtbo-base := jlq_jr510.dtb
jr510_c3qr.dtbo-base := jlq_jr510.dtb

dsi_panel_boe_nt36525b.dtbo-base := jlq_jr510.dtb
dsi_panel_boe_nt36525b_lv.dtbo-base := jlq_jr510.dtb
dsi_panel_truly_ft8006saa.dtbo-base := jlq_jr510.dtb
dsi_panel_truly_ft8006saa_lv.dtbo-base := jlq_jr510.dtb

jr510_svc01.dtbo-base := jlq_jr510.dtb
jr510_svc02.dtbo-base := jlq_jr510.dtb
jr510_svc03.dtbo-base := jlq_jr510.dtb
jr510_svc04.dtbo-base := jlq_jr510.dtb

always +=  $(dtbo)