# SPDX-License-Identifier: GPL-2.0

ccflags-y := -I $(srctree)/kernel/irq/
obj-$(CONFIG_JLQ_WATCHDOG) += jlq_wdt.o
obj-$(CONFIG_JLQ_SYSDUMP) += jlq_sysdump.o
obj-$(CONFIG_JLQ_SYSDUMP) += jlq_slave_dummy.o
obj-$(CONFIG_JLQ_ISR_MONITOR) += jlq_isr_monitor.o

