# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#
#

obj-$(CONFIG_CPUFREQ_DT_JLQ_PLATDEV)	+= cpufreq-dt-jlq-platdev.o
obj-$(CONFIG_CPUFREQ_DT_JLQ)	+= cpufreq-dt-jlq.o
obj-$(CONFIG_CPUFREQ_DT_JLQ)	+= cpufreq-proc.o
