# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019, The Linux Foundation. All rights reserved.

export CONFIG_SPECTRA_CAMERA=m
export CONFIG_SPECTRA_TFE=m
export CONFIG_SPECTRA_ISP=m
export CONFIG_SPECTRA_SENSOR=m
export CONFIG_SPECTRA_OPE=m
