# SPDX-License-Identifier: GPL-2.0-only

# fpc fingerprint drivers
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/

# goodix fingerprint drivers
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/

# silead fingerprint drivers
obj-$(CONFIG_SILEAD_FP)			+= silead/
obj-$(CONFIG_SILEAD_FP_PLATFORM)	+= silead/

