# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I $(srctree)/drivers/thermal
obj-$(CONFIG_JLQ_QTI_ADC_TM) += qti-adc-tm.o
qti-adc-tm-y += adc-tm.o adc-tm-common.o adc-tm5.o adc-tm7.o
obj-$(CONFIG_JLQ_QTI_BCL_SOC_DRIVER) += bcl_soc.o
obj-$(CONFIG_JLQ_QCOM_SPMI_TEMP_ALARM)	+= qcom-spmi-temp-alarm.o
obj-$(CONFIG_JLQ_QTI_BCL_PMIC5) += bcl_pmic5.o
