/*
 * JLQ Devices clock dtsi include
 *
 * Copyright 2018~2020 JLQ Technology Co.,
 * Ltd. or its affiliates. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __JR510_REGS_TOP_CRG_H
#define __JR510_REGS_TOP_CRG_H

#define TOP_PLL_LOCK_TIME                        (0x0000)
#define DDR_PHY_CLOCKMUX                         (0x0004)
#define DDR_PHY_CLOCKGATE                        (0x0008)
#define PLL_DDR_CFG0                             (0x000C)
#define PLL_DDR_CFG1                             (0x0010)
#define PLL_DDR_CFG2                             (0x0014)
#define DDR_PLL_MIF_CONF0                        (0x0018)
#define DDR_PLL_MIF_CONF1                        (0x001C)
#define DDR_CRG_CG_SFCTL0                        (0x0020)
#define DDR_CRG_CG_SFCTL2                        (0x0024)
#define DDR_CRG_MX_SFCTL                         (0x0028)
#define PLL_CPU_BIG_CFG0                         (0x0030)
#define PLL_CPU_BIG_CFG1                         (0x0034)
#define PLL_CPU_BIG_CFG2                         (0x0038)
#define PLL_CPU_LITTLE_CFG0                      (0x0040)
#define PLL_CPU_LITTLE_CFG1                      (0x0044)
#define PLL_CPU_LITTLE_CFG2                      (0x0048)
#define PLL_DSU_CFG0                             (0x0050)
#define PLL_DSU_CFG1                             (0x0054)
#define PLL_DSU_CFG2                             (0x005c)
#define PLL_I2S_CFG0                             (0x0060)
#define PLL_I2S_CFG1                             (0x0064)
#define PLL_I2S_CFG2                             (0x0068)
#define PLL_OPT_CFG0                             (0x0070)
#define PLL_OPT_CFG1                             (0x0074)
#define PLL_OPT_CFG2                             (0x0078)
#define PLL_COMM_CFG0                            (0x0080)
#define PLL_COMM_CFG1                            (0x0084)
#define PLL_COMM_CFG2                            (0x0088)
#define FIXDIV_CLK_FORCE_ON                      (0x0090)
#define TOP_CLK_24P576M_CTL                      (0x00a0)
#define TOP_CLK_22P5792M_CTL                     (0x00a4)
#define CPU_LOW_CLK_CTL                          (0x00b0)
#define CPU_BIG_CORE_CLK_SRC_MX_CTL              (0x00b4)
#define CPU_LITTLE_CORE_CLK_SRC_MX_CTL           (0x00b8)
#define CPU_DSU_CLK_SRC_MX_CTL                   (0x00bc)
#define DDR_P3_AXI_CLK_SRC_MX_CTL                (0x00c0)
#define DDR_P0_AXI_CLK_SRC_CDIV_CTL              (0x00c4)
#define TOP_BUS_CLK_SRC_MX_CTL                   (0x00c8)
#define DDR_BUS0_CLK_SRC_MX_CTL                  (0x00d0)
#define DDR_BUS1_CLK_SRC_MX_CTL                  (0x00d4)
#define DDR_BUS2_CLK_SRC_MX_CTL                  (0x00d8)
#define CM4_CORECLK_SRC_MX_CTL                   (0x00dc)
#define ADSP_CORECLK_SRC_MX_CTL                  (0x00e0)
#define AUDIO_BUS_CLK_SRC_MX_CTL                 (0x00e4)
#define FBE_BUS_CLK_SRC_MX_CTL                   (0x00e8)
#define GPU_CLK_SRC_MX_CTL                       (0x00ec)
#define AI_CORECLK_SRC_MX_CTL                    (0x00f0)
#define VDSP_CORECLK_SRC_MX_CTL                  (0x00f4)
#define VPU_CORECLK_SRC_MX_CTL                   (0x00f8)
#define CETI_CORECLK_SRC_MX_CTL                  (0x00fc)
#define PXL_CLK_SRC_MX_CTL                       (0x0100)
#define EMMC_BCLK_SRC_MX_CTL                     (0x0104)
#define SDIO0_BCLK_SRC_MX_CTL                    (0x0108)
#define SDIO1_BCLK_SRC_MX_CTL                    (0x010C)
#define I2S0_CLK_SRC_MX_CTL                      (0x0110)
#define I2S1_CLK_SRC_MX_CTL                      (0x0114)
#define I2C3_IC_CLK_SRC_MX_CTL                   (0x0118)
#define I2C4_IC_CLK_SRC_MX_CTL                   (0x011C)
#define I2C5_IC_CLK_SRC_MX_CTL                   (0x0120)
#define I2C6_IC_CLK_SRC_MX_CTL                   (0x0124)
#define TIMER0_1_CLK_SRC_MX_CTL                  (0x0128)
#define TIMER0_2_CLK_SRC_MX_CTL                  (0x012C)
#define WDT00_TCLK_SRC_MX_CTL                    (0x0130)
#define WDT01_TCLK_SRC_MX_CTL                    (0x0134)
#define WDT1_TCLK_SRC_MX_CTL                     (0x0138)
#define WDT2_TCLK_SRC_MX_CTL                     (0x013C)
#define WDT3_TCLK_SRC_MX_CTL                     (0x0140)
#define BOLERO_MCLK_2X_SRC_MX_CTL                (0x0144)
#define CS_CLK_CG_CTL                            (0x0160)
#define GIC_CLK_CG_CTL                           (0x0164)
#define ADSP_CORECLK_CDIV_CTL                    (0x0168)
#define AUDIO_BUS_CLK_CDIV_CTL                   (0x016c)
#define CETI_CORE_CLK_GDIV_CTL                   (0x0174)
#define PXL_CLK_GDIV_CTL                         (0x0178)
#define GPIO_CLK_CG_CTL                          (0x017C)
#define PWM_CLK_CG_CTL                           (0x0180)
#define SSI0_CLK_CDIV_CTL                        (0x0184)
#define SSI1_CLK_CDIV_CTL                        (0x0188)
#define SSI2_CLK_CDIV_CTL                        (0x018C)
#define EMMC_CLKTX_CDIV_CTL                      (0x0190)
#define EMMC_CLKTX_CDIV_STAT                     (0x0194)
#define SDIO0_CLKTX_CDIV_CTL                     (0x0198)
#define SDIO0_CLKTX_CDIV_STAT                    (0x019C)
#define SDIO1_CLKTX_CDIV_CTL                     (0x01A0)
#define SDIO1_CLKTX_CDIV_STAT                    (0x01A4)
#define I2S0_CLK_CDIV_CTL                        (0x01A8)
#define I2S1_CLK_CDIV_CTL                        (0x01AC)
#define GPU_CRG_CTL0                             (0x01B0)
#define GPU_CRG_CTL1                             (0x01B4)
#define GPU_CRG_CTL2                             (0x01B8)
#define TOP_MODULE_CLK_CG_CTL0                   (0x01BC)
#define TOP_MODULE_CLK_CG_CTL1                   (0x01C0)
#define TOP_MODULE_CLK_CG_CTL2                   (0x01C4)
#define TOP_MODULE_CLK_CG_CTL3                   (0x01C8)
#define FBE_CLK_CDIV_CTL                         (0x01CC)
#define QTANG_CLK_CTL                            (0x01D0)
#define CPU_DSU_CLK_SRC_DIV3_CDIV_CTL            (0x01D4)
#define QTANG_CLK_CTL1                           (0x01D8)
#define UART_CLK_PROTECT_CTL                     (0x01E0)
#define BUS_LP_CTL                               (0x0400)
#define BUS_LP_EN_CTL0                           (0x0404)
#define BUS_LP_EN_CTL1                           (0x0408)
#define BUS_LP_EN_CTL2                           (0x040c)
#define BUS_LP_EN_CTL3                           (0x0410)
#define DDR_TOP_LP_EN_CTL0                       (0x0414)
#define CPU_SYS_LP_EN_CTL0                       (0x0418)
#define BUS_LP_ST0                               (0X041c)
#define BUS_LP_ST1                               (0X0420)
#define BUS_LP_ST2                               (0X0424)
#define BUS_LP_ST3                               (0X0428)
#define BUS_LP_ST4                               (0X042c)
#define BUS_LP_ST5                               (0X0430)
#define BUS_LP_ST6                               (0X0434)
#define BUS_LP_ST7                               (0x0438)
#define DDR_TOP_LP_ST                            (0x043c)
#define CPU_SYS_LP_ST                            (0x0440)
#define TOP_USB_RST_CTL                          (0x0200)
#define TOP_AI_RST_CTL                           (0x0204)
#define TOP_VPU_RST_CTL                          (0x0208)
#define TOP_VDSP_RST_CTL                         (0x020C)
#define TOP_GPU_RST_CTL                          (0x0210)
#define TOP_HBLK_RST_CTL                         (0x0214)
#define TOP_DISPLAY_RST_CTL                      (0x0218)
#define TOP_AUDIO_RST_CTL                        (0x021C)
#define TOP_M4_RST_CTL                           (0x0220)
#define TOP_MODULE_RST_CTL0                      (0x0240)
#define TOP_MODULE_RST_CTL1                      (0x0244)
#define TOP_MODULE_RST_CTL2                      (0x0248)
#define TOP_MODULE_RST_CTL3                      (0x024C)
#define TOP_MODULE_RST_CTL4                      (0x0250)
#define DDR_RST_SFCTL0                           (0x0260)
#define DDR_RST_SFCTL1                           (0x0264)
#define DDR_RST_SFCTL2                           (0x0268)
#define TOP_DDR_RST_HWCTL                        (0x026C)
#define QTANG_RST_CTL                            (0x02A0)
#define SUBSYS_ACTIVE_STAT                       (0x0444)
#define TOP_CLKOUT_CTL                           (0x01F0)
#define TOP_CRG_INTR_RAW                         (0x0500)
#define TOP_CRG_INTR_EN                          (0x0504)
#define TOP_CRG_INTR_MASK                        (0x0508)
#define TOP_CRG_INTR_STATUS                      (0x050C)
#define TOP_CHIP_RSTN_CTL0                       (0x0300)
#define TOP_CHIP_RSTN_CTL1                       (0x0304)
#define TOP_CHIP_RSTN_CTL2                       (0x0308)
#define TOP_SFRST_CTL                            (0x030C)
#define TOP_ABNORMAL_RST_STAT                    (0x0310)
#define START_REG0                               (0x0314)

#define TOP_CHIP_RSTN_CTL3			 (0x0320)
#define TOP_CHIP_RSTN_CTL4			 (0x0324)
#define TOP_CHIP_RSTN_CTL5			 (0x0328)

#define TRBG_RANDOM_DATA_CLK_CDIV_CTL		 (0x0604)
#define TRBG_RANDOM_DATA_CLK_CDIV_CTL_1		 (0x0608)

#define PLL_OUT_ATE_EN				 (0x060C)

#define BOLERO_CLK_CTL				 (0x0610)

#define PWR_MASK(len)			((1 << len) - 1)
#define PWR_BIT_SFT(x)			(x)
#define PWR_WEBIT_SFT(x, offset)	(PWR_BIT_SFT(x) + offset)
#define PWR_WEBIT_DEF(x)		PWR_WEBIT_SFT(x, 16)
#define PWR_WEBIT_NONE			(0)

#define PLL_MASK(len)			PWR_MASK(len)

#define PLL_K_SFT                       (16)
#define PLL_M_SFT                       (6)
#define PLL_P_SFT                       (0)
#define PLL_S_SFT                       (0)
#define PLL_PD_SFT                      (1)
#define PLL_ADJ_SFT                     (0)
#define PLL_K_WEBIT_DEF                 PWR_WEBIT_DEF(16)

#define MIF_M_SFT                       (6)
#define MIF_M_WEBIT_DEF                 PWR_WEBIT_DEF(6)
#define MIF_P_SFT                       (0)
#define MIF_P_WEBIT_DEF                 PWR_WEBIT_DEF(0)
#define MIF_S_SFT                       (16)
#define MIF_S_WEBIT_DEF                 PWR_WEBIT_DEF(16)
#define MIF_PD_SFT                      (5)
#define MIF_PD_WEBIT_DEF                PWR_WEBIT_DEF(5)
#define MIF_ADJ_SFT                     (4)
#define MIF_ADJ_WEBIT_DEF               PWR_WEBIT_DEF(4)

#define	JLQ_TOP_CRG		1
#define	JLQ_AI_SYSCTRL		2
#define	JLQ_CM4_SYSCTRL		3
#define	JLQ_DISPLAY_SYSCTRL	4
#define	JLQ_HBLK_SYSCTRL	5
#define	JLQ_VDSP_SYSCTRL	6
#define	JLQ_VPU_SYSCTRL		7
#define	JLQ_AUDIO_SYSCTRL	8

#endif /* __JR510_REGS_TOP_CRG_H. */

