# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_JLQ_CAMERA_THERMAL)		:= jlq_cam_thermal.o
jlq_cam_thermal-y := cam_thermal.o cam-cdev.o

obj-$(CONFIG_JLQ_CAMERA_THERMAL_TEST)	+= jlq_cam_thermal_test.o
jlq_cam_thermal_test-y := cam_thermal_test.o cam-cdev-test.o
