# SPDX-License-Identifier: GPL-2.0-only

#
# Makefile for the MSM specific device drivers.
#

obj-$(CONFIG_IPA3) += ipa_fmwk/
obj-$(CONFIG_MSM_GENI_SE) += msm-geni-se.o
obj-$(CONFIG_USB_BAM) += usb_bam.o
obj-$(CONFIG_SPS) += sps/
obj-$(CONFIG_VETH_IPA) += veth_ipa/
