# SPDX-License-Identifier: GPL-2.0

ccflags-y			:= -I$(srctree)/drivers/usb/gadget/
ccflags-y			+= -I$(srctree)/drivers/usb/gadget/function/

obj-$(CONFIG_USB_F_CDEV)	+= f_cdev.o
obj-$(CONFIG_USB_F_GSI)		+= f_gsi.o
