# Makefile for the focaltech touchscreen drivers.
focaltech-objs := focaltech_core.o
focaltech-objs += focaltech_ex_fun.o
focaltech-objs += focaltech_ex_mode.o
focaltech-objs += focaltech_gesture.o
focaltech-objs += focaltech_esdcheck.o
focaltech-objs += focaltech_point_report_check.o
focaltech-objs += focaltech_flash.o
focaltech-objs += focaltech_spi.o
focaltech-objs += focaltech_test.o
focaltech-objs += focaltech_test_ini.o
focaltech-objs += focaltech_test_ft8006s_ab.o
focaltech-objs += focaltech_test_ft8006s_an.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech.o
