# Copyright 2018~2019 JLQ Technology Co., Ltd. or its affiliates.
# All rights reserved.
#
# This program is free software;
# you can redistribute it and/or modify it under the terms of
# the GNU General Public License version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
#
#
obj-$(CONFIG_DSI_TRANSMITTER_JLQ) += jlq_dsi_panel.o jlq_dsi_transmitter.o
obj-$(CONFIG_DRM_VIRT_ENCODER) += drm_virtual_encoder.o
obj-$(CONFIG_BACKLIGHT_JLQ) += jlq_backlight.o
