# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_JLQ_CHARGER_MANAGER) += jlq_cm.o
jlq_cm-y += jlq_battery_profile.o jlq_charger_manager.o jlq_cm_voter.o  qcom_battery_sysfs.o
obj-$(CONFIG_JLQ_SD7601) +=  sd7601.o
obj-$(CONFIG_JLQ_SGM4154X) += sgm4154x_charger.o
obj-$(CONFIG_JLQ_SH36610X) +=  sh36610x.o
sh36610x-y +=  sh366101_fg.o
